# Generated by Django 3.0.3 on 2020-03-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0005_place_restaurant_waiter'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parson',
            table='people',
        ),
    ]
