# Generated by Django 3.0.3 on 2020-03-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0010_auto_20200303_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'get_latest_by': '-release_date'},
        ),
    ]
