# Generated by Django 3.0.3 on 2020-03-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0014_auto_20200303_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='album',
            order_with_respect_to='artist',
        ),
    ]
