# Generated by Django 3.0.3 on 2020-03-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0015_auto_20200303_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='album',
            order_with_respect_to=None,
        ),
    ]
