# Generated by Django 3.0.3 on 2020-03-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0016_auto_20200303_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['?']},
        ),
    ]
