# Generated by Django 3.0.3 on 2020-03-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0017_auto_20200303_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['release_date']},
        ),
    ]
