# Generated by Django 3.0.3 on 2020-03-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0018_auto_20200303_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['release_date'], 'permissions': [('can_sell_album', 'Can Sell Album')]},
        ),
    ]
