# Generated by Django 3.0.3 on 2020-03-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0019_auto_20200303_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAlbum',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nikka.album',),
        ),
    ]
