# Generated by Django 3.0.3 on 2020-03-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0020_myalbum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myalbum',
            options={'ordering': ['-release_date']},
        ),
    ]
