# Generated by Django 3.0.3 on 2020-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0022_myparson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('tag', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MyParson',
        ),
    ]
