# Generated by Django 3.0.3 on 2020-03-03 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0024_auto_20200303_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nikka.Piece')),
                ('article_name', models.CharField(max_length=50)),
            ],
            bases=('nikka.piece',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nikka.Piece')),
                ('book_name', models.CharField(max_length=50)),
            ],
            bases=('nikka.piece',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='nikka.Article')),
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nikka.Book')),
                ('review_date', models.DateField(default=datetime.date(2020, 3, 3))),
            ],
            bases=('nikka.book', 'nikka.article'),
        ),
    ]
