# Generated by Django 3.0.3 on 2020-03-03 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0025_article_book_piece_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(verbose_name=datetime.date(2020, 3, 3)),
        ),
    ]
