# Generated by Django 3.0.3 on 2020-03-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikka', '0027_author_blog_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tegline',
            new_name='tagline',
        ),
    ]
